services:
  api:
    build:
      context: ./recommendation-service
      dockerfile: Dockerfile
    volumes:
      - ./recommendation-service/src:/app/src
    ports:
      - "8000:8000"
    env_file:
      - ./recommendation-service/.env
    depends_on:
      - db

  api2:
    build:
      context: ./recommendation-service
      dockerfile: Dockerfile
    volumes:
      - ./recommendation-service/src:/app/src
    ports:
      - "8001:8000"
    env_file:
      - ./recommendation-service/.env
    depends_on:
      - db

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: recommendations_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  ngnix:
    build:
        context: ./nginx
        dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - api2

volumes:
  pgdata:
