apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: movies-platform
data:
  nginx.conf: |
    worker_processes  1;
    events { worker_connections 1024; }
    http {
      upstream api_cluster {
        server recommendation:8000;
        keepalive 16;
      }
      server {
        listen 80;
        location / {
          proxy_pass http://api_cluster;
          proxy_http_version 1.1;
          proxy_set_header Connection "";
        }
      }
    }
